### ISSUE TITLE
重新拉取仓库以整理杂乱的合并请求与Commits(WIP)

### ISSUE THREAD

**Issue by RainyHallways** [rnhws-Team/PhoenixBuilder-Achieved#180]
# ⚠️请勿将此仓库直接删除

- [x] 创建新仓库将默认分支命名为`Major`(只拉去一个分支[main])
- [x] 将此`Mainfull`分支内的核心修改迁移至新仓库(检测更新规则，启动提醒[Banner]，Github Actions) ⚠️Action 文件内请修改分支名称
- [x] 将此仓库与新仓库重命名
- [x] 将此仓库设为Template状态

**Comment by Happy2018new** [comment]
但我没有新仓库的协作者权限

**Comment by RainyHallways** [comment]
> 但我没有新仓库的协作者权限

已添加

**Comment by Happy2018new** [comment]
ok

**Comment by Happy2018new** [comment]
但我注意到上游有一些较大更改，所以我现在先管管上游
